# Generated by Django 4.2.16 on 2024-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service_description',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service_description',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service_description',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service_description',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_description',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_description',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
