# Generated by Django 4.2.16 on 2024-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedescription',
            name='image',
            field=models.ImageField(upload_to='service_description'),
        ),
    ]
