<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-09-26 11:43
=======
# Generated by Django 4.2.16 on 2024-09-19 04:57
>>>>>>> d20b4f3 (Commit xabari)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Certificates',
=======
            name='Certificate',
>>>>>>> d20b4f3 (Commit xabari)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
<<<<<<< HEAD
                ('image', models.ImageField(upload_to='certificates')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ_Category',
=======
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Faq_category',
>>>>>>> d20b4f3 (Commit xabari)
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
=======
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('profession', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
>>>>>>> d20b4f3 (Commit xabari)
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('image', models.ImageField(upload_to='partners')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='teams')),
=======
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('profession', models.TextField()),
                ('created_at', models.DateTimeField()),
>>>>>>> d20b4f3 (Commit xabari)
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=50)),
=======
                ('title', models.CharField(max_length=100)),
>>>>>>> d20b4f3 (Commit xabari)
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('faq_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faq_category')),
=======
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('answers', models.TextField()),
                ('faq_page', models.CharField(max_length=50)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.faq_category')),
>>>>>>> d20b4f3 (Commit xabari)
            ],
        ),
    ]
