# Generated by Django 4.2.16 on 2024-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answers_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answers_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answers_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='questions_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='questions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='questions_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq_category',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faq_category',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faq_category',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='full_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='full_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='full_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='profession_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='profession_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='profession_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
